#!/bin/bash

# same as watch-proj, but automatically reruns the EXITed jobs

proj=${1:-default}
sec=${2:-60}

reset (){
    exited=$(jbinfo -proj $proj | grep EXIT | awk '{print $1}')
    [ -z "$exited" ] || jbadmin -reset $exited
    if [ $sec -eq 0 ]
    then
        exit
    else
        sleep $sec
    fi
}

reset

while jbinfo -proj $proj | grep -q "RUN\|AVAIL"
do
    echo "[$(date)]  Project $proj still running (recheck after $sec sec)"
    reset
done

echo "[$(date)]  Project $proj finished"
